<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks and truncate before seeding
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('locations')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $locations = [
            ['id' => 1,   'name' => 'INDIA',                      'parent_id' => 0, 'status' => '1'],
            ['id' => 2,   'name' => 'ANDAMAN AND NICOBAR ISLANDS', 'parent_id' => 1,  'status' => '1'],
            ['id' => 3,   'name' => 'ANDHRA PRADESH',              'parent_id' => 1,  'status' => '1'],
            ['id' => 4,   'name' => 'ARUNACHAL PRADESH',           'parent_id' => 1,  'status' => '1'],
            ['id' => 5,   'name' => 'ASSAM',                       'parent_id' => 1,  'status' => '1'],
            ['id' => 6,   'name' => 'BIHAR',                       'parent_id' => 1,  'status' => '1'],
            ['id' => 7,   'name' => 'CHANDIGARH',                  'parent_id' => 1,  'status' => '1'],
            ['id' => 8,   'name' => 'CHHATTISGARH',                'parent_id' => 1,  'status' => '1'],
            ['id' => 9,   'name' => 'DADRA AND NAGAR HAVELI',      'parent_id' => 1,  'status' => '1'],
            ['id' => 10,  'name' => 'DAMAN AND DIU',               'parent_id' => 1,  'status' => '1'],
            ['id' => 11,  'name' => 'DELHI',                       'parent_id' => 1,  'status' => '1'],
            ['id' => 12,  'name' => 'GOA',                         'parent_id' => 1,  'status' => '1'],
            ['id' => 13,  'name' => 'GUJARAT',                     'parent_id' => 1,  'status' => '1'],
            ['id' => 14,  'name' => 'HARYANA',                     'parent_id' => 1,  'status' => '1'],
            ['id' => 15,  'name' => 'HIMACHAL PRADESH',            'parent_id' => 1,  'status' => '1'],
            ['id' => 16,  'name' => 'JAMMU AND KASHMIR',           'parent_id' => 1,  'status' => '1'],
            ['id' => 17,  'name' => 'JHARKHAND',                   'parent_id' => 1,  'status' => '1'],
            ['id' => 18,  'name' => 'KARNATAKA',                   'parent_id' => 1,  'status' => '1'],
            ['id' => 19,  'name' => 'KERALA',                      'parent_id' => 1,  'status' => '1'],
            ['id' => 20,  'name' => 'LAKSHADWEEP',                 'parent_id' => 1,  'status' => '1'],
            ['id' => 21,  'name' => 'MADHYA PRADESH',              'parent_id' => 1,  'status' => '1'],
            ['id' => 22,  'name' => 'MAHARASHTRA',                 'parent_id' => 1,  'status' => '1'],
            ['id' => 23,  'name' => 'MANIPUR',                     'parent_id' => 1,  'status' => '1'],
            ['id' => 24,  'name' => 'MEGHALAYA',                   'parent_id' => 1,  'status' => '1'],
            ['id' => 25,  'name' => 'MIZORAM',                     'parent_id' => 1,  'status' => '1'],
            ['id' => 26,  'name' => 'NAGALAND',                    'parent_id' => 1,  'status' => '1'],
            ['id' => 27,  'name' => 'ORISSA',                      'parent_id' => 1,  'status' => '1'],
            ['id' => 28,  'name' => 'PUDUCHERRY',                  'parent_id' => 1,  'status' => '1'],
            ['id' => 29,  'name' => 'PUNJAB',                      'parent_id' => 1,  'status' => '1'],
            ['id' => 30,  'name' => 'RAJASTHAN',                   'parent_id' => 1,  'status' => '1'],
            ['id' => 31,  'name' => 'SIKKIM',                      'parent_id' => 1,  'status' => '1'],
            ['id' => 32,  'name' => 'TAMIL NADU',                  'parent_id' => 1,  'status' => '1'],
            ['id' => 33,  'name' => 'TRIPURA',                     'parent_id' => 1,  'status' => '1'],
            ['id' => 34,  'name' => 'UTTAR PRADESH',               'parent_id' => 1,  'status' => '1'],
            ['id' => 35,  'name' => 'UTTARAKHAND',                 'parent_id' => 1,  'status' => '1'],
            ['id' => 36,  'name' => 'WEST BENGAL',                 'parent_id' => 1,  'status' => '1'],
            ['id' => 37,  'name' => 'JORHAT',                      'parent_id' => 5,  'status' => '1'],
            ['id' => 39,  'name' => 'NIZAMGARH',                   'parent_id' => 37, 'status' => '1'],
            ['id' => 40,  'name' => 'CIVIL LINES',                 'parent_id' => 37, 'status' => '1'],
            ['id' => 41,  'name' => 'LUCKNOW',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 42,  'name' => 'INDIRANAGAR',                 'parent_id' => 41, 'status' => '1'],
            ['id' => 43,  'name' => 'ALIGARH',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 44,  'name' => 'AGRA',                        'parent_id' => 34, 'status' => '1'],
            ['id' => 45,  'name' => 'PATNA',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 46,  'name' => 'DEOGHAR',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 47,  'name' => 'MUZAFFARPUR',                 'parent_id' => 6,  'status' => '1'],
            ['id' => 48,  'name' => 'MORADABAD',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 49,  'name' => 'KARIMGANJ',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 50,  'name' => 'SHAHARANPUR',                 'parent_id' => 34, 'status' => '1'],
            ['id' => 51,  'name' => 'DARBHANGA',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 52,  'name' => 'JAMSHEDPUR',                  'parent_id' => 17, 'status' => '1'],
            ['id' => 53,  'name' => 'BAREILLY',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 54,  'name' => 'BASTI',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 55,  'name' => 'ETAH',                        'parent_id' => 34, 'status' => '1'],
            ['id' => 56,  'name' => 'ETAWA',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 57,  'name' => 'BHAGALPUR',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 58,  'name' => 'VARANASI',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 59,  'name' => 'ALLAHABAD',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 60,  'name' => 'FAIZABAD',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 61,  'name' => 'GONDA',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 62,  'name' => 'GAZIPUR',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 63,  'name' => 'ARARIA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 64,  'name' => 'ARRAH',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 65,  'name' => 'BAGAHA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 66,  'name' => 'BEGUSARAI',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 67,  'name' => 'BETTIAH',                     'parent_id' => 6,  'status' => '1'],
            ['id' => 68,  'name' => 'BUXAR',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 69,  'name' => 'CHAPRA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 70,  'name' => 'DEHRIONSONE',                 'parent_id' => 6,  'status' => '1'],
            ['id' => 71,  'name' => 'DINAPURNIZAMAT',              'parent_id' => 6,  'status' => '1'],
            ['id' => 72,  'name' => 'GAYA',                        'parent_id' => 6,  'status' => '1'],
            ['id' => 73,  'name' => 'GOPALGANJ',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 74,  'name' => 'HAJIPUR',                     'parent_id' => 6,  'status' => '1'],
            ['id' => 75,  'name' => 'JAMALPUR',                    'parent_id' => 6,  'status' => '1'],
            ['id' => 76,  'name' => 'JAMUI',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 77,  'name' => 'JEHANABAD',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 78,  'name' => 'KATIHAR',                     'parent_id' => 6,  'status' => '1'],
            ['id' => 79,  'name' => 'KISHANGANJ',                  'parent_id' => 6,  'status' => '1'],
            ['id' => 80,  'name' => 'LAKHISARAI',                  'parent_id' => 6,  'status' => '1'],
            ['id' => 81,  'name' => 'MADHUBANI',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 82,  'name' => 'MOKAMA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 83,  'name' => 'MOTIHARI',                    'parent_id' => 6,  'status' => '1'],
            ['id' => 84,  'name' => 'MUNGER',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 85,  'name' => 'NAWADA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 86,  'name' => 'PHULWARISHARIF',              'parent_id' => 6,  'status' => '1'],
            ['id' => 87,  'name' => 'PURNIA',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 88,  'name' => 'SAHARSA',                     'parent_id' => 6,  'status' => '1'],
            ['id' => 89,  'name' => 'SAMASTIPUR',                  'parent_id' => 6,  'status' => '1'],
            ['id' => 90,  'name' => 'SASARAM',                     'parent_id' => 6,  'status' => '1'],
            ['id' => 91,  'name' => 'SITAMARHI',                   'parent_id' => 6,  'status' => '1'],
            ['id' => 92,  'name' => 'SUPAUL',                      'parent_id' => 6,  'status' => '1'],
            ['id' => 93,  'name' => 'NEW DELHI',                   'parent_id' => 11, 'status' => '1'],
            ['id' => 94,  'name' => 'GOLMURI',                     'parent_id' => 52, 'status' => '1'],
            ['id' => 95,  'name' => 'KUSHINAGER',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 98,  'name' => 'CHARBAGH',                    'parent_id' => 41, 'status' => '1'],
            ['id' => 99,  'name' => 'KANPUR',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 100, 'name' => 'KOKRAJHAR',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 101, 'name' => 'DIPHU',                       'parent_id' => 5,  'status' => '1'],
            ['id' => 102, 'name' => 'LAKHIMPUR',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 104, 'name' => 'GUNTUR',                      'parent_id' => 3,  'status' => '1'],
            ['id' => 105, 'name' => 'ABU ROAD',                    'parent_id' => 30, 'status' => '1'],
            ['id' => 106, 'name' => 'BHOPAL',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 107, 'name' => 'AMBEDKAR NAGAR',              'parent_id' => 34, 'status' => '1'],
            ['id' => 108, 'name' => 'BARABANKI',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 109, 'name' => 'GORAKHPUR',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 110, 'name' => 'DEORIA',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 112, 'name' => 'CHANDAULI',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 113, 'name' => 'MAU',                         'parent_id' => 34, 'status' => '1'],
            ['id' => 114, 'name' => 'ALMORA',                      'parent_id' => 35, 'status' => '1'],
            ['id' => 115, 'name' => 'BAGESHWAR',                   'parent_id' => 35, 'status' => '1'],
            ['id' => 116, 'name' => 'CHAMOLI',                     'parent_id' => 35, 'status' => '1'],
            ['id' => 117, 'name' => 'CHAMPAWAT',                   'parent_id' => 35, 'status' => '1'],
            ['id' => 118, 'name' => 'DEHRADUN',                    'parent_id' => 35, 'status' => '1'],
            ['id' => 119, 'name' => 'HARIDWAR',                    'parent_id' => 35, 'status' => '1'],
            ['id' => 120, 'name' => 'NAINITAL',                    'parent_id' => 35, 'status' => '1'],
            ['id' => 121, 'name' => 'PAURI GARHWAL',               'parent_id' => 35, 'status' => '1'],
            ['id' => 122, 'name' => 'PITHORAGARH',                 'parent_id' => 35, 'status' => '1'],
            ['id' => 123, 'name' => 'RUDRAPRAYAG',                 'parent_id' => 35, 'status' => '1'],
            ['id' => 124, 'name' => 'TEHRI GARHWAL',               'parent_id' => 35, 'status' => '1'],
            ['id' => 125, 'name' => 'UDHAM SINGH NAGAR',           'parent_id' => 35, 'status' => '1'],
            ['id' => 126, 'name' => 'UTTARKASHI',                  'parent_id' => 35, 'status' => '1'],
            ['id' => 127, 'name' => 'CAR NICOBAR',                 'parent_id' => 2,  'status' => '1'],
            ['id' => 128, 'name' => 'GREAT NICOBAR ISLAND',        'parent_id' => 2,  'status' => '1'],
            ['id' => 129, 'name' => 'NANCOWRY',                    'parent_id' => 2,  'status' => '1'],
            ['id' => 130, 'name' => 'ANANTAPUR',                   'parent_id' => 3,  'status' => '1'],
            ['id' => 131, 'name' => 'CHITTOOR',                    'parent_id' => 3,  'status' => '1'],
            ['id' => 132, 'name' => 'EAST GODAVARI',               'parent_id' => 3,  'status' => '1'],
            ['id' => 133, 'name' => 'KADAPA',                      'parent_id' => 3,  'status' => '1'],
            ['id' => 134, 'name' => 'KRISHNA',                     'parent_id' => 3,  'status' => '1'],
            ['id' => 135, 'name' => 'KURNOOL',                     'parent_id' => 3,  'status' => '1'],
            ['id' => 136, 'name' => 'NELLORE',                     'parent_id' => 3,  'status' => '1'],
            ['id' => 137, 'name' => 'PRAKASAM',                    'parent_id' => 3,  'status' => '1'],
            ['id' => 138, 'name' => 'SRIKAKULAM',                  'parent_id' => 3,  'status' => '1'],
            ['id' => 139, 'name' => 'VISAKHAPATNAM',               'parent_id' => 3,  'status' => '1'],
            ['id' => 140, 'name' => 'VIZIANAGARAM',                'parent_id' => 3,  'status' => '1'],
            ['id' => 141, 'name' => 'WEST GODAVARI',               'parent_id' => 3,  'status' => '1'],
            ['id' => 142, 'name' => 'HAWAI',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 143, 'name' => 'CHANGLANG',                   'parent_id' => 4,  'status' => '1'],
            ['id' => 144, 'name' => 'SEPPA',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 145, 'name' => 'PASIGHAT',                    'parent_id' => 4,  'status' => '1'],
            ['id' => 146, 'name' => 'TEZU',                        'parent_id' => 4,  'status' => '1'],
            ['id' => 147, 'name' => 'LONGDING',                    'parent_id' => 4,  'status' => '1'],
            ['id' => 148, 'name' => 'ZIRO',                        'parent_id' => 4,  'status' => '1'],
            ['id' => 149, 'name' => 'YUPIA',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 150, 'name' => 'TAWANG TOWN',                 'parent_id' => 4,  'status' => '1'],
            ['id' => 151, 'name' => 'KHONSA',                      'parent_id' => 4,  'status' => '1'],
            ['id' => 152, 'name' => 'ROING',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 153, 'name' => 'YINGKIONG',                   'parent_id' => 4,  'status' => '1'],
            ['id' => 154, 'name' => 'DAPORIJO',                    'parent_id' => 4,  'status' => '1'],
            ['id' => 155, 'name' => 'BOMDILA',                     'parent_id' => 4,  'status' => '1'],
            ['id' => 156, 'name' => 'ALONG',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 157, 'name' => 'ANINI',                       'parent_id' => 4,  'status' => '1'],
            ['id' => 158, 'name' => 'KOLORIANG',                   'parent_id' => 4,  'status' => '1'],
            ['id' => 159, 'name' => 'BARPETA',                     'parent_id' => 5,  'status' => '1'],
            ['id' => 160, 'name' => 'BONGAIGAON',                  'parent_id' => 5,  'status' => '1'],
            ['id' => 161, 'name' => 'SILCHAR',                     'parent_id' => 5,  'status' => '1'],
            ['id' => 162, 'name' => 'MANGALDAI',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 163, 'name' => 'DHEMAJI',                     'parent_id' => 5,  'status' => '1'],
            ['id' => 164, 'name' => 'DHUBRI',                      'parent_id' => 5,  'status' => '1'],
            ['id' => 165, 'name' => 'DIBRUGARH',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 166, 'name' => 'GOALPARA',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 167, 'name' => 'GOLAGHAT',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 168, 'name' => 'HAILAKANDI',                  'parent_id' => 5,  'status' => '1'],
            ['id' => 169, 'name' => 'MORIGAON',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 170, 'name' => 'NAGAON',                      'parent_id' => 5,  'status' => '1'],
            ['id' => 171, 'name' => 'NALBARI',                     'parent_id' => 5,  'status' => '1'],
            ['id' => 172, 'name' => 'HAFLONG',                     'parent_id' => 5,  'status' => '1'],
            ['id' => 173, 'name' => 'SIVASAGAR',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 174, 'name' => 'TEZPUR',                      'parent_id' => 5,  'status' => '1'],
            ['id' => 175, 'name' => 'TINSUKIA',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 176, 'name' => 'AMINGAON',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 177, 'name' => 'GUWAHATI',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 178, 'name' => 'MUSHALPUR',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 179, 'name' => 'UDALGURI',                    'parent_id' => 5,  'status' => '1'],
            ['id' => 180, 'name' => 'KALAIGAON',                   'parent_id' => 5,  'status' => '1'],
            ['id' => 181, 'name' => 'BISHWANATH CHARIALI',         'parent_id' => 5,  'status' => '1'],
            ['id' => 182, 'name' => 'HOJAI',                       'parent_id' => 5,  'status' => '1'],
            ['id' => 183, 'name' => 'SONARI',                      'parent_id' => 5,  'status' => '1'],
            ['id' => 184, 'name' => 'HATSINGIMARI',                'parent_id' => 5,  'status' => '1'],
            ['id' => 185, 'name' => 'BANKA',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 186, 'name' => 'BALOD',                       'parent_id' => 8,  'status' => '1'],
            ['id' => 187, 'name' => 'BALODA BAZAR',                'parent_id' => 8,  'status' => '1'],
            ['id' => 188, 'name' => 'BALRAMPUR',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 189, 'name' => 'JAGDALPUR',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 190, 'name' => 'BEMETARA',                    'parent_id' => 8,  'status' => '1'],
            ['id' => 191, 'name' => 'BIJAPUR',                     'parent_id' => 8,  'status' => '1'],
            ['id' => 192, 'name' => 'BILASPUR',                    'parent_id' => 8,  'status' => '1'],
            ['id' => 193, 'name' => 'DANTEWADA',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 194, 'name' => 'DHAMTARI',                    'parent_id' => 8,  'status' => '1'],
            ['id' => 195, 'name' => 'DURG',                        'parent_id' => 8,  'status' => '1'],
            ['id' => 196, 'name' => 'GARIABAND',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 197, 'name' => 'NAILA JANJGIR',               'parent_id' => 8,  'status' => '1'],
            ['id' => 198, 'name' => 'JASHPUR',                     'parent_id' => 8,  'status' => '1'],
            ['id' => 199, 'name' => 'KAWARDHA',                    'parent_id' => 8,  'status' => '1'],
            ['id' => 200, 'name' => 'KANKER',                      'parent_id' => 8,  'status' => '1'],
            ['id' => 201, 'name' => 'KONDAGAON',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 202, 'name' => 'KORBA',                       'parent_id' => 8,  'status' => '1'],
            ['id' => 203, 'name' => 'BAIKUNTHPUR',                 'parent_id' => 8,  'status' => '1'],
            ['id' => 204, 'name' => 'MAHASAMUND',                  'parent_id' => 8,  'status' => '1'],
            ['id' => 205, 'name' => 'MUNGELI',                     'parent_id' => 8,  'status' => '1'],
            ['id' => 206, 'name' => 'NARAYANPUR',                  'parent_id' => 8,  'status' => '1'],
            ['id' => 207, 'name' => 'RAIGARH',                     'parent_id' => 8,  'status' => '1'],
            ['id' => 208, 'name' => 'RAIPUR',                      'parent_id' => 8,  'status' => '1'],
            ['id' => 209, 'name' => 'RAJNANDGAON',                 'parent_id' => 8,  'status' => '1'],
            ['id' => 210, 'name' => 'SUKMA',                       'parent_id' => 8,  'status' => '1'],
            ['id' => 211, 'name' => 'SURAJPUR',                    'parent_id' => 8,  'status' => '1'],
            ['id' => 212, 'name' => 'AMBIKAPUR',                   'parent_id' => 8,  'status' => '1'],
            ['id' => 213, 'name' => 'MAPUSA',                      'parent_id' => 12, 'status' => '1'],
            ['id' => 214, 'name' => 'PANAJI',                      'parent_id' => 12, 'status' => '1'],
            ['id' => 215, 'name' => 'MARGOA',                      'parent_id' => 12, 'status' => '1'],
            ['id' => 216, 'name' => 'PONDA',                       'parent_id' => 12, 'status' => '1'],
            ['id' => 217, 'name' => 'VASCO',                       'parent_id' => 12, 'status' => '1'],
            ['id' => 218, 'name' => 'AHMEDABAD',                   'parent_id' => 13, 'status' => '1'],
            ['id' => 219, 'name' => 'AMRELI',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 220, 'name' => 'ANAND',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 221, 'name' => 'MODASA',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 222, 'name' => 'PALANPUR',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 223, 'name' => 'BHARUCH',                     'parent_id' => 13, 'status' => '1'],
            ['id' => 224, 'name' => 'BHAVNAGAR',                   'parent_id' => 13, 'status' => '1'],
            ['id' => 225, 'name' => 'BOTAD',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 226, 'name' => 'CHHOTA UDAIPUR',              'parent_id' => 13, 'status' => '1'],
            ['id' => 227, 'name' => 'DAHOD',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 228, 'name' => 'AHWA',                        'parent_id' => 13, 'status' => '1'],
            ['id' => 229, 'name' => 'KHAMBHALIA',                  'parent_id' => 13, 'status' => '1'],
            ['id' => 230, 'name' => 'GANDHINAGAR',                 'parent_id' => 13, 'status' => '1'],
            ['id' => 231, 'name' => 'VERAVAL',                     'parent_id' => 13, 'status' => '1'],
            ['id' => 232, 'name' => 'JAMNAGAR',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 233, 'name' => 'JUNAGADH',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 234, 'name' => 'BHUJ',                        'parent_id' => 13, 'status' => '1'],
            ['id' => 235, 'name' => 'NADIAD',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 236, 'name' => 'LUNAVADA',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 237, 'name' => 'MEHSANA',                     'parent_id' => 13, 'status' => '1'],
            ['id' => 238, 'name' => 'MORBI',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 239, 'name' => 'RAJPIPLA',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 240, 'name' => 'NAVSARI',                     'parent_id' => 13, 'status' => '1'],
            ['id' => 241, 'name' => 'GODHRA',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 242, 'name' => 'PATAN',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 243, 'name' => 'PORBANDAR',                   'parent_id' => 13, 'status' => '1'],
            ['id' => 244, 'name' => 'RAJKOT',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 245, 'name' => 'HIMMATNAGAR',                 'parent_id' => 13, 'status' => '1'],
            ['id' => 246, 'name' => 'SURAT',                       'parent_id' => 13, 'status' => '1'],
            ['id' => 247, 'name' => 'SURENDRANAGAR',               'parent_id' => 13, 'status' => '1'],
            ['id' => 248, 'name' => 'TAPI',                        'parent_id' => 13, 'status' => '1'],
            ['id' => 249, 'name' => 'VADODARA',                    'parent_id' => 13, 'status' => '1'],
            ['id' => 250, 'name' => 'VALSAD',                      'parent_id' => 13, 'status' => '1'],
            ['id' => 251, 'name' => 'AMBALA',                      'parent_id' => 14, 'status' => '1'],
            ['id' => 252, 'name' => 'BHIWANI',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 253, 'name' => 'FARIDABAD',                   'parent_id' => 14, 'status' => '1'],
            ['id' => 254, 'name' => 'FATEHABAD',                   'parent_id' => 14, 'status' => '1'],
            ['id' => 255, 'name' => 'GURGAON',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 256, 'name' => 'HISAR',                       'parent_id' => 14, 'status' => '1'],
            ['id' => 257, 'name' => 'JHAJJAR',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 258, 'name' => 'JIND',                        'parent_id' => 14, 'status' => '1'],
            ['id' => 259, 'name' => 'KAITHAL',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 260, 'name' => 'KARNAL',                      'parent_id' => 14, 'status' => '1'],
            ['id' => 261, 'name' => 'KURUKSHETRA',                 'parent_id' => 14, 'status' => '1'],
            ['id' => 262, 'name' => 'MAHENDRAGARH',                'parent_id' => 14, 'status' => '1'],
            ['id' => 263, 'name' => 'NUH',                         'parent_id' => 14, 'status' => '1'],
            ['id' => 264, 'name' => 'PALWAL',                      'parent_id' => 14, 'status' => '1'],
            ['id' => 265, 'name' => 'PANCHKULA',                   'parent_id' => 14, 'status' => '1'],
            ['id' => 266, 'name' => 'PANIPAT',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 267, 'name' => 'REWARI',                      'parent_id' => 14, 'status' => '1'],
            ['id' => 268, 'name' => 'ROHTAK',                      'parent_id' => 14, 'status' => '1'],
            ['id' => 269, 'name' => 'SIRSA',                       'parent_id' => 14, 'status' => '1'],
            ['id' => 270, 'name' => 'SONIPAT',                     'parent_id' => 14, 'status' => '1'],
            ['id' => 271, 'name' => 'YAMUNANAGAR',                 'parent_id' => 14, 'status' => '1'],
            ['id' => 272, 'name' => 'BILASPUR',                    'parent_id' => 15, 'status' => '1'],
            ['id' => 273, 'name' => 'CHAMBA',                      'parent_id' => 15, 'status' => '1'],
            ['id' => 274, 'name' => 'HAMIRPUR',                    'parent_id' => 15, 'status' => '1'],
            ['id' => 275, 'name' => 'KANGRA',                      'parent_id' => 15, 'status' => '1'],
            ['id' => 276, 'name' => 'KINNAUR',                     'parent_id' => 15, 'status' => '1'],
            ['id' => 277, 'name' => 'KULLU',                       'parent_id' => 15, 'status' => '1'],
            ['id' => 278, 'name' => 'LAHAUL AND SPITI',            'parent_id' => 15, 'status' => '1'],
            ['id' => 279, 'name' => 'MANDI',                       'parent_id' => 15, 'status' => '1'],
            ['id' => 280, 'name' => 'SHIMLA',                      'parent_id' => 15, 'status' => '1'],
            ['id' => 281, 'name' => 'SIRMAUR',                     'parent_id' => 15, 'status' => '1'],
            ['id' => 282, 'name' => 'SOLAN',                       'parent_id' => 15, 'status' => '1'],
            ['id' => 283, 'name' => 'UNA',                         'parent_id' => 15, 'status' => '1'],
            ['id' => 284, 'name' => 'JAMMU',                       'parent_id' => 16, 'status' => '1'],
            ['id' => 285, 'name' => 'DODA',                        'parent_id' => 16, 'status' => '1'],
            ['id' => 286, 'name' => 'KISHTWAR',                    'parent_id' => 16, 'status' => '1'],
            ['id' => 287, 'name' => 'RAJOURI',                     'parent_id' => 16, 'status' => '1'],
            ['id' => 288, 'name' => 'REASI',                       'parent_id' => 16, 'status' => '1'],
            ['id' => 289, 'name' => 'UDHAMPUR',                    'parent_id' => 16, 'status' => '1'],
            ['id' => 290, 'name' => 'RAMBAN',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 291, 'name' => 'KATHUA',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 292, 'name' => 'SAMBA',                       'parent_id' => 16, 'status' => '1'],
            ['id' => 293, 'name' => 'POONCH',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 294, 'name' => 'SRINAGAR',                    'parent_id' => 16, 'status' => '1'],
            ['id' => 295, 'name' => 'ANANTNAG',                    'parent_id' => 16, 'status' => '1'],
            ['id' => 296, 'name' => 'TELANGANA',                   'parent_id' => 1,  'status' => '1'],
            ['id' => 297, 'name' => 'KULGAM',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 298, 'name' => 'PULWAMA',                     'parent_id' => 16, 'status' => '1'],
            ['id' => 299, 'name' => 'SHOPIAN',                     'parent_id' => 16, 'status' => '1'],
            ['id' => 300, 'name' => 'BUDGAM',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 301, 'name' => 'GANDERBAL',                   'parent_id' => 16, 'status' => '1'],
            ['id' => 302, 'name' => 'BANDIPORA',                   'parent_id' => 16, 'status' => '1'],
            ['id' => 303, 'name' => 'BARAMULLA',                   'parent_id' => 16, 'status' => '1'],
            ['id' => 304, 'name' => 'KUPWARA',                     'parent_id' => 16, 'status' => '1'],
            ['id' => 305, 'name' => 'KARGIL',                      'parent_id' => 16, 'status' => '1'],
            ['id' => 306, 'name' => 'LEH',                         'parent_id' => 16, 'status' => '1'],
            ['id' => 307, 'name' => 'GARHWA',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 308, 'name' => 'GIRIDIH',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 309, 'name' => 'SIMDEGA',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 310, 'name' => 'JAMTARA',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 311, 'name' => 'PALAMU',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 312, 'name' => 'LATEHAR',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 313, 'name' => 'CHATRA',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 314, 'name' => 'HAZARIBAGH',                  'parent_id' => 17, 'status' => '1'],
            ['id' => 315, 'name' => 'KODERMA',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 316, 'name' => 'RAMGARH',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 317, 'name' => 'BOKARO',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 318, 'name' => 'DHANBAD',                     'parent_id' => 17, 'status' => '1'],
            ['id' => 319, 'name' => 'LOHARDAGA',                   'parent_id' => 17, 'status' => '1'],
            ['id' => 320, 'name' => 'GUMLA',                       'parent_id' => 17, 'status' => '1'],
            ['id' => 321, 'name' => 'RANCHI',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 322, 'name' => 'KHUNTI',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 323, 'name' => 'WEST SINGHBHUM',              'parent_id' => 17, 'status' => '1'],
            ['id' => 324, 'name' => 'SARAIKELA KHARSAWAN',         'parent_id' => 17, 'status' => '1'],
            ['id' => 325, 'name' => 'EAST SINGHBHUM',              'parent_id' => 17, 'status' => '1'],
            ['id' => 326, 'name' => 'DUMKA',                       'parent_id' => 17, 'status' => '1'],
            ['id' => 327, 'name' => 'PAKUR',                       'parent_id' => 17, 'status' => '1'],
            ['id' => 328, 'name' => 'GODDA',                       'parent_id' => 17, 'status' => '1'],
            ['id' => 329, 'name' => 'SAHEBGANJ',                   'parent_id' => 17, 'status' => '1'],
            ['id' => 330, 'name' => 'BAGALKOT',                    'parent_id' => 18, 'status' => '1'],
            ['id' => 331, 'name' => 'BENGALURU',                   'parent_id' => 18, 'status' => '1'],
            ['id' => 332, 'name' => 'BELAGAVI',                    'parent_id' => 18, 'status' => '1'],
            ['id' => 333, 'name' => 'BALLARI',                     'parent_id' => 18, 'status' => '1'],
            ['id' => 334, 'name' => 'BIDAR',                       'parent_id' => 18, 'status' => '1'],
            ['id' => 335, 'name' => 'VIJAYAPURA',                  'parent_id' => 18, 'status' => '1'],
            ['id' => 336, 'name' => 'CHAMARAJANAGAR',              'parent_id' => 18, 'status' => '1'],
            ['id' => 337, 'name' => 'CHIKBALLAPUR',                'parent_id' => 18, 'status' => '1'],
            ['id' => 338, 'name' => 'CHIKKAMAGALURU',              'parent_id' => 18, 'status' => '1'],
            ['id' => 339, 'name' => 'CHITRADURGA',                 'parent_id' => 18, 'status' => '1'],
            ['id' => 340, 'name' => 'MANGALURU',                   'parent_id' => 18, 'status' => '1'],
            ['id' => 341, 'name' => 'DAVANAGERE',                  'parent_id' => 18, 'status' => '1'],
            ['id' => 342, 'name' => 'DHARWAD',                     'parent_id' => 18, 'status' => '1'],
            ['id' => 343, 'name' => 'GADAG',                       'parent_id' => 18, 'status' => '1'],
            ['id' => 344, 'name' => 'KALABURAGI',                  'parent_id' => 18, 'status' => '1'],
            ['id' => 345, 'name' => 'HASSAN',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 346, 'name' => 'HAVERI',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 347, 'name' => 'MADIKERI',                    'parent_id' => 18, 'status' => '1'],
            ['id' => 348, 'name' => 'KOLAR',                       'parent_id' => 18, 'status' => '1'],
            ['id' => 349, 'name' => 'KOPPAL',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 350, 'name' => 'MANDYA',                      'parent_id' => 17, 'status' => '1'],
            ['id' => 351, 'name' => 'MYSURU',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 352, 'name' => 'RAICHUR',                     'parent_id' => 18, 'status' => '1'],
            ['id' => 353, 'name' => 'RAMANAGARA',                  'parent_id' => 18, 'status' => '1'],
            ['id' => 354, 'name' => 'SHIVAMOGGA',                  'parent_id' => 18, 'status' => '1'],
            ['id' => 355, 'name' => 'TUMAKURU',                    'parent_id' => 18, 'status' => '1'],
            ['id' => 356, 'name' => 'UDUPI',                       'parent_id' => 18, 'status' => '1'],
            ['id' => 357, 'name' => 'KARWAR',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 358, 'name' => 'YADGIR',                      'parent_id' => 18, 'status' => '1'],
            ['id' => 359, 'name' => 'ALAPPUZHA',                   'parent_id' => 19, 'status' => '1'],
            ['id' => 360, 'name' => 'KAKKANAD',                    'parent_id' => 19, 'status' => '1'],
            ['id' => 361, 'name' => 'PAINAVU',                     'parent_id' => 19, 'status' => '1'],
            ['id' => 362, 'name' => 'KANNUR',                      'parent_id' => 19, 'status' => '1'],
            ['id' => 363, 'name' => 'KASARAGOD',                   'parent_id' => 19, 'status' => '1'],
            ['id' => 364, 'name' => 'KOLLAM',                      'parent_id' => 19, 'status' => '1'],
            ['id' => 365, 'name' => 'KOTTAYAM',                    'parent_id' => 19, 'status' => '1'],
            ['id' => 366, 'name' => 'KOZHIKODE',                   'parent_id' => 19, 'status' => '1'],
            ['id' => 367, 'name' => 'MALAPPURAM',                  'parent_id' => 19, 'status' => '1'],
            ['id' => 368, 'name' => 'PALAKKAD',                    'parent_id' => 19, 'status' => '1'],
            ['id' => 369, 'name' => 'PATHANAMTHITTA',              'parent_id' => 19, 'status' => '1'],
            ['id' => 370, 'name' => 'THIRUVANANTHAPURAM',          'parent_id' => 19, 'status' => '1'],
            ['id' => 371, 'name' => 'THRISSUR',                    'parent_id' => 19, 'status' => '1'],
            ['id' => 372, 'name' => 'KALPETTA',                    'parent_id' => 19, 'status' => '1'],
            ['id' => 373, 'name' => 'AGARMALWA',                   'parent_id' => 21, 'status' => '1'],
            ['id' => 374, 'name' => 'ALIRAJPUR',                   'parent_id' => 21, 'status' => '1'],
            ['id' => 375, 'name' => 'ANUPPUR',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 376, 'name' => 'ASHOKNAGAR',                  'parent_id' => 21, 'status' => '1'],
            ['id' => 377, 'name' => 'BALAGHAT',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 378, 'name' => 'BARWANI',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 379, 'name' => 'BETUL',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 380, 'name' => 'BHIND',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 381, 'name' => 'BURHANPUR',                   'parent_id' => 21, 'status' => '1'],
            ['id' => 382, 'name' => 'CHHATARPUR',                  'parent_id' => 21, 'status' => '1'],
            ['id' => 383, 'name' => 'CHHINDWARA',                  'parent_id' => 21, 'status' => '1'],
            ['id' => 384, 'name' => 'DAMOH',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 385, 'name' => 'DATIA',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 386, 'name' => 'DEWAS',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 387, 'name' => 'DHAR',                        'parent_id' => 21, 'status' => '1'],
            ['id' => 388, 'name' => 'DINDORI',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 389, 'name' => 'GUNA',                        'parent_id' => 21, 'status' => '1'],
            ['id' => 390, 'name' => 'GWALIOR',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 391, 'name' => 'HARDA',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 392, 'name' => 'HOSHANGABAD',                 'parent_id' => 21, 'status' => '1'],
            ['id' => 393, 'name' => 'INDORE',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 394, 'name' => 'JABALPUR',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 395, 'name' => 'JHABUA',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 396, 'name' => 'KATNI',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 397, 'name' => 'KHANDWA',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 398, 'name' => 'KHARGONE',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 399, 'name' => 'MANDLA',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 400, 'name' => 'MANDSAUR',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 401, 'name' => 'MORENA',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 402, 'name' => 'NARSINGHPUR',                 'parent_id' => 21, 'status' => '1'],
            ['id' => 403, 'name' => 'NEEMUCH',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 404, 'name' => 'PANNA',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 405, 'name' => 'RAJGARH',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 406, 'name' => 'RATLAM',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 407, 'name' => 'REWA',                        'parent_id' => 21, 'status' => '1'],
            ['id' => 408, 'name' => 'SAGAR',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 409, 'name' => 'SATNA',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 410, 'name' => 'SEHORE',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 411, 'name' => 'SEONI',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 412, 'name' => 'SINGRAULI',                   'parent_id' => 21, 'status' => '1'],
            ['id' => 413, 'name' => 'SHAHDOL',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 414, 'name' => 'SHAJAPUR',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 415, 'name' => 'SHEOPUR',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 416, 'name' => 'SHIVPURI',                    'parent_id' => 21, 'status' => '1'],
            ['id' => 417, 'name' => 'SIDHI',                       'parent_id' => 21, 'status' => '1'],
            ['id' => 418, 'name' => 'TIKAMGARH',                   'parent_id' => 21, 'status' => '1'],
            ['id' => 419, 'name' => 'UJJAIN',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 420, 'name' => 'UMARIA',                      'parent_id' => 21, 'status' => '1'],
            ['id' => 421, 'name' => 'VIDISHA',                     'parent_id' => 21, 'status' => '1'],
            ['id' => 422, 'name' => 'AHMEDNAGAR',                  'parent_id' => 22, 'status' => '1'],
            ['id' => 423, 'name' => 'AKOLA',                       'parent_id' => 22, 'status' => '1'],
            ['id' => 424, 'name' => 'AMRAVATI',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 425, 'name' => 'AURANGABAD',                  'parent_id' => 22, 'status' => '1'],
            ['id' => 426, 'name' => 'BEED',                        'parent_id' => 22, 'status' => '1'],
            ['id' => 427, 'name' => 'BHANDARA',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 428, 'name' => 'BULDHANA',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 429, 'name' => 'CHANDRAPUR',                  'parent_id' => 22, 'status' => '1'],
            ['id' => 430, 'name' => 'DHULE',                       'parent_id' => 22, 'status' => '1'],
            ['id' => 431, 'name' => 'GADCHIROLI',                  'parent_id' => 22, 'status' => '1'],
            ['id' => 432, 'name' => 'GONDIA',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 433, 'name' => 'HINGOLI',                     'parent_id' => 22, 'status' => '1'],
            ['id' => 434, 'name' => 'THANE',                       'parent_id' => 22, 'status' => '1'],
            ['id' => 435, 'name' => 'JALNA',                       'parent_id' => 22, 'status' => '1'],
            ['id' => 436, 'name' => 'KOLHAPUR',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 437, 'name' => 'LATUR',                       'parent_id' => 22, 'status' => '1'],
            ['id' => 438, 'name' => 'MUMBAI',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 439, 'name' => 'BANDRA',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 440, 'name' => 'NAGPUR',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 441, 'name' => 'NANDED',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 442, 'name' => 'NANDURBAR',                   'parent_id' => 22, 'status' => '1'],
            ['id' => 443, 'name' => 'NASHIK',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 444, 'name' => 'OSMANABAD',                   'parent_id' => 22, 'status' => '1'],
            ['id' => 445, 'name' => 'PARBHANI',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 446, 'name' => 'PUNE',                        'parent_id' => 22, 'status' => '1'],
            ['id' => 447, 'name' => 'ALIBAG',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 448, 'name' => 'RATNAGIRI',                   'parent_id' => 22, 'status' => '1'],
            ['id' => 449, 'name' => 'SANGLI',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 450, 'name' => 'SATARA',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 451, 'name' => 'OROS',                        'parent_id' => 22, 'status' => '1'],
            ['id' => 452, 'name' => 'SOLAPUR',                     'parent_id' => 22, 'status' => '1'],
            ['id' => 453, 'name' => 'WARDHA',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 454, 'name' => 'WASHIM',                      'parent_id' => 22, 'status' => '1'],
            ['id' => 455, 'name' => 'YAVATMAL',                    'parent_id' => 22, 'status' => '1'],
            ['id' => 456, 'name' => 'PALGHAR',                     'parent_id' => 22, 'status' => '1'],
            ['id' => 457, 'name' => 'BISHNUPUR',                   'parent_id' => 23, 'status' => '1'],
            ['id' => 458, 'name' => 'CHURACHANDPUR',               'parent_id' => 23, 'status' => '1'],
            ['id' => 459, 'name' => 'CHANDEL',                     'parent_id' => 23, 'status' => '1'],
            ['id' => 460, 'name' => 'POROMPAT',                    'parent_id' => 23, 'status' => '1'],
            ['id' => 461, 'name' => 'SENAPATI',                    'parent_id' => 23, 'status' => '1'],
            ['id' => 462, 'name' => 'TAMENGLONG',                  'parent_id' => 23, 'status' => '1'],
            ['id' => 463, 'name' => 'THOUBAL',                     'parent_id' => 23, 'status' => '1'],
            ['id' => 464, 'name' => 'UKHRUL',                      'parent_id' => 23, 'status' => '1'],
            ['id' => 465, 'name' => 'LAMPHELPAT',                  'parent_id' => 23, 'status' => '1'],
            ['id' => 466, 'name' => 'WILLIAMNAGAR',                'parent_id' => 24, 'status' => '1'],
            ['id' => 467, 'name' => 'SHILLONG',                    'parent_id' => 24, 'status' => '1'],
            ['id' => 468, 'name' => 'JOWAI',                       'parent_id' => 24, 'status' => '1'],
            ['id' => 469, 'name' => 'NONGPOH',                     'parent_id' => 24, 'status' => '1'],
            ['id' => 470, 'name' => 'BAGHMARA',                    'parent_id' => 24, 'status' => '1'],
            ['id' => 471, 'name' => 'TURA',                        'parent_id' => 24, 'status' => '1'],
            ['id' => 472, 'name' => 'NONGSTOIN',                   'parent_id' => 24, 'status' => '1'],
            ['id' => 473, 'name' => 'AIZAWL',                      'parent_id' => 25, 'status' => '1'],
            ['id' => 474, 'name' => 'KOLASIB',                     'parent_id' => 25, 'status' => '1'],
            ['id' => 475, 'name' => 'LUNGLEI',                     'parent_id' => 25, 'status' => '1'],
            ['id' => 476, 'name' => 'LAWNGTLAI',                   'parent_id' => 25, 'status' => '1'],
            ['id' => 477, 'name' => 'MAMIT',                       'parent_id' => 25, 'status' => '1'],
            ['id' => 478, 'name' => 'SIAHA',                       'parent_id' => 25, 'status' => '1'],
            ['id' => 479, 'name' => 'SERCHHIP',                    'parent_id' => 25, 'status' => '1'],
            ['id' => 480, 'name' => 'CHAMPHAI',                    'parent_id' => 25, 'status' => '1'],
            ['id' => 481, 'name' => 'DIMAPUR',                     'parent_id' => 26, 'status' => '1'],
            ['id' => 482, 'name' => 'KIPHIRE',                     'parent_id' => 26, 'status' => '1'],
            ['id' => 483, 'name' => 'KOHIMA',                      'parent_id' => 26, 'status' => '1'],
            ['id' => 484, 'name' => 'LONGLENG',                    'parent_id' => 26, 'status' => '1'],
            ['id' => 485, 'name' => 'MOKOKCHUNG',                  'parent_id' => 26, 'status' => '1'],
            ['id' => 486, 'name' => 'MON',                         'parent_id' => 26, 'status' => '1'],
            ['id' => 487, 'name' => 'PEREN',                       'parent_id' => 26, 'status' => '1'],
            ['id' => 488, 'name' => 'PHEK',                        'parent_id' => 26, 'status' => '1'],
            ['id' => 489, 'name' => 'TUENSANG',                    'parent_id' => 26, 'status' => '1'],
            ['id' => 490, 'name' => 'WOKHA',                       'parent_id' => 26, 'status' => '1'],
            ['id' => 491, 'name' => 'ZUNHEBOTO',                   'parent_id' => 26, 'status' => '1'],
            ['id' => 492, 'name' => 'ANUGUL',                      'parent_id' => 27, 'status' => '1'],
            ['id' => 493, 'name' => 'BOUDH',                       'parent_id' => 27, 'status' => '1'],
            ['id' => 494, 'name' => 'BHADRAK',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 495, 'name' => 'BALANGIR',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 496, 'name' => 'BARGARH',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 497, 'name' => 'BALASORE',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 498, 'name' => 'CUTTACK',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 499, 'name' => 'DEBAGARH',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 500, 'name' => 'DHENKANAL',                   'parent_id' => 27, 'status' => '1'],
            ['id' => 501, 'name' => 'CHHATRAPUR',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 502, 'name' => 'PARALAKHEMUNDI',              'parent_id' => 27, 'status' => '1'],
            ['id' => 503, 'name' => 'JHARSUGUDA',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 504, 'name' => 'JAJPUR',                      'parent_id' => 27, 'status' => '1'],
            ['id' => 505, 'name' => 'JAGATSINGHAPUR',              'parent_id' => 27, 'status' => '1'],
            ['id' => 506, 'name' => 'KHORDHA',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 507, 'name' => 'KENDUJHAR',                   'parent_id' => 27, 'status' => '1'],
            ['id' => 508, 'name' => 'BHAWANIPATNA',                'parent_id' => 27, 'status' => '1'],
            ['id' => 509, 'name' => 'PHULBANI',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 510, 'name' => 'KORAPUT',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 511, 'name' => 'KENDRAPARA',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 512, 'name' => 'MALKANGIRI',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 513, 'name' => 'BARIPADA',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 514, 'name' => 'NABARANGAPUR',                'parent_id' => 27, 'status' => '1'],
            ['id' => 515, 'name' => 'NUAPADA',                     'parent_id' => 27, 'status' => '1'],
            ['id' => 516, 'name' => 'NAYAGARH',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 517, 'name' => 'PURI',                        'parent_id' => 27, 'status' => '1'],
            ['id' => 518, 'name' => 'RAYAGADA',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 519, 'name' => 'SAMBALPUR',                   'parent_id' => 27, 'status' => '1'],
            ['id' => 520, 'name' => 'SUBARNAPUR',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 521, 'name' => 'SUNDARGARH',                  'parent_id' => 27, 'status' => '1'],
            ['id' => 522, 'name' => 'BHUBANESWAR',                 'parent_id' => 27, 'status' => '1'],
            ['id' => 523, 'name' => 'KARAIKAL',                    'parent_id' => 28, 'status' => '1'],
            ['id' => 524, 'name' => 'MAHE',                        'parent_id' => 28, 'status' => '1'],
            ['id' => 525, 'name' => 'YANAM',                       'parent_id' => 28, 'status' => '1'],
            ['id' => 526, 'name' => 'HOSHIARPUR',                  'parent_id' => 29, 'status' => '1'],
            ['id' => 527, 'name' => 'JALANDHAR',                   'parent_id' => 29, 'status' => '1'],
            ['id' => 528, 'name' => 'AMRITSAR',                    'parent_id' => 29, 'status' => '1'],
            ['id' => 529, 'name' => 'BARNALA',                     'parent_id' => 29, 'status' => '1'],
            ['id' => 530, 'name' => 'BATHINDA',                    'parent_id' => 29, 'status' => '1'],
            ['id' => 531, 'name' => 'FARIDKOT',                    'parent_id' => 29, 'status' => '1'],
            ['id' => 532, 'name' => 'FATEHGARH SAHIB',             'parent_id' => 29, 'status' => '1'],
            ['id' => 533, 'name' => 'FAZILKA',                     'parent_id' => 29, 'status' => '1'],
            ['id' => 534, 'name' => 'FIROZPUR',                    'parent_id' => 29, 'status' => '1'],
            ['id' => 535, 'name' => 'GURDASPUR',                   'parent_id' => 29, 'status' => '1'],
            ['id' => 536, 'name' => 'LUDHIANA',                    'parent_id' => 29, 'status' => '1'],
            ['id' => 537, 'name' => 'KAPURTHALA',                  'parent_id' => 29, 'status' => '1'],
            ['id' => 538, 'name' => 'MANSA',                       'parent_id' => 29, 'status' => '1'],
            ['id' => 539, 'name' => 'MOGA',                        'parent_id' => 29, 'status' => '1'],
            ['id' => 540, 'name' => 'MOHALI',                      'parent_id' => 29, 'status' => '1'],
            ['id' => 541, 'name' => 'ROPAR',                       'parent_id' => 29, 'status' => '1'],
            ['id' => 542, 'name' => 'SRI MUKTSAR SAHIB',           'parent_id' => 29, 'status' => '1'],
            ['id' => 543, 'name' => 'NAWAN SHAHR',                 'parent_id' => 29, 'status' => '1'],
            ['id' => 544, 'name' => 'SANGRUR',                     'parent_id' => 29, 'status' => '1'],
            ['id' => 545, 'name' => 'PATIALA',                     'parent_id' => 29, 'status' => '1'],
            ['id' => 546, 'name' => 'PATHANKOT',                   'parent_id' => 29, 'status' => '1'],
            ['id' => 547, 'name' => 'TARN TARAN',                  'parent_id' => 29, 'status' => '1'],
            ['id' => 548, 'name' => 'AJMER',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 549, 'name' => 'ALWAR',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 550, 'name' => 'BANSWARA',                    'parent_id' => 30, 'status' => '1'],
            ['id' => 551, 'name' => 'BARAN',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 552, 'name' => 'BARMER',                      'parent_id' => 30, 'status' => '1'],
            ['id' => 553, 'name' => 'BHARATPUR',                   'parent_id' => 30, 'status' => '1'],
            ['id' => 554, 'name' => 'BHILWARA',                    'parent_id' => 30, 'status' => '1'],
            ['id' => 555, 'name' => 'BIKANER',                     'parent_id' => 30, 'status' => '1'],
            ['id' => 556, 'name' => 'BUNDI',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 557, 'name' => 'CHITTORGARH',                 'parent_id' => 30, 'status' => '1'],
            ['id' => 558, 'name' => 'CHURU',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 559, 'name' => 'DAUSA',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 560, 'name' => 'DHOLPUR',                     'parent_id' => 30, 'status' => '1'],
            ['id' => 561, 'name' => 'DUNGARPUR',                   'parent_id' => 30, 'status' => '1'],
            ['id' => 562, 'name' => 'HANUMANGARH',                 'parent_id' => 30, 'status' => '1'],
            ['id' => 563, 'name' => 'JAIPUR',                      'parent_id' => 30, 'status' => '1'],
            ['id' => 564, 'name' => 'JAISALMER',                   'parent_id' => 30, 'status' => '1'],
            ['id' => 565, 'name' => 'JALORE',                      'parent_id' => 30, 'status' => '1'],
            ['id' => 566, 'name' => 'JHALAWAR',                    'parent_id' => 30, 'status' => '1'],
            ['id' => 567, 'name' => 'JHUNJHUNU',                   'parent_id' => 30, 'status' => '1'],
            ['id' => 568, 'name' => 'JODHPUR',                     'parent_id' => 30, 'status' => '1'],
            ['id' => 569, 'name' => 'KARAULI',                     'parent_id' => 30, 'status' => '1'],
            ['id' => 570, 'name' => 'KOTA',                        'parent_id' => 30, 'status' => '1'],
            ['id' => 571, 'name' => 'NAGAUR',                      'parent_id' => 30, 'status' => '1'],
            ['id' => 572, 'name' => 'PALI',                        'parent_id' => 30, 'status' => '1'],
            ['id' => 573, 'name' => 'PRATAPGARH',                  'parent_id' => 30, 'status' => '1'],
            ['id' => 574, 'name' => 'RAJSAMAND',                   'parent_id' => 30, 'status' => '1'],
            ['id' => 575, 'name' => 'SAWAI MADHOPUR',              'parent_id' => 30, 'status' => '1'],
            ['id' => 576, 'name' => 'SIKAR',                       'parent_id' => 30, 'status' => '1'],
            ['id' => 577, 'name' => 'SIROHI',                      'parent_id' => 30, 'status' => '1'],
            ['id' => 578, 'name' => 'SRI GANGANAGAR',              'parent_id' => 30, 'status' => '1'],
            ['id' => 579, 'name' => 'TONK',                        'parent_id' => 30, 'status' => '1'],
            ['id' => 580, 'name' => 'UDAIPUR',                     'parent_id' => 30, 'status' => '1'],
            ['id' => 581, 'name' => 'GANGTOK',                     'parent_id' => 31, 'status' => '1'],
            ['id' => 582, 'name' => 'MANGAN',                      'parent_id' => 31, 'status' => '1'],
            ['id' => 583, 'name' => 'NAMCHI',                      'parent_id' => 31, 'status' => '1'],
            ['id' => 584, 'name' => 'GEYZING',                     'parent_id' => 31, 'status' => '1'],
            ['id' => 585, 'name' => 'ARIYALUR',                    'parent_id' => 32, 'status' => '1'],
            ['id' => 586, 'name' => 'CHENNAI',                     'parent_id' => 32, 'status' => '1'],
            ['id' => 587, 'name' => 'COIMBATORE',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 588, 'name' => 'CUDDALORE',                   'parent_id' => 32, 'status' => '1'],
            ['id' => 589, 'name' => 'DHARMAPURI',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 590, 'name' => 'DINDIGUL',                    'parent_id' => 32, 'status' => '1'],
            ['id' => 591, 'name' => 'ERODE',                       'parent_id' => 32, 'status' => '1'],
            ['id' => 592, 'name' => 'KANCHIPURAM',                 'parent_id' => 32, 'status' => '1'],
            ['id' => 593, 'name' => 'NAGERCOIL',                   'parent_id' => 32, 'status' => '1'],
            ['id' => 594, 'name' => 'KARUR',                       'parent_id' => 32, 'status' => '1'],
            ['id' => 595, 'name' => 'KRISHNAGIRI',                 'parent_id' => 32, 'status' => '1'],
            ['id' => 596, 'name' => 'MADURAI',                     'parent_id' => 32, 'status' => '1'],
            ['id' => 597, 'name' => 'NAGAPATTINAM',                'parent_id' => 32, 'status' => '1'],
            ['id' => 598, 'name' => 'NAMAKKAL',                    'parent_id' => 32, 'status' => '1'],
            ['id' => 599, 'name' => 'OOTY',                        'parent_id' => 32, 'status' => '1'],
            ['id' => 600, 'name' => 'PERAMBALUR',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 601, 'name' => 'PUDUKOTTAI',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 602, 'name' => 'RAMANATHAPURAM',              'parent_id' => 32, 'status' => '1'],
            ['id' => 603, 'name' => 'SALEM',                       'parent_id' => 32, 'status' => '1'],
            ['id' => 604, 'name' => 'SIVAGANGA',                   'parent_id' => 32, 'status' => '1'],
            ['id' => 605, 'name' => 'THANJAVUR',                   'parent_id' => 32, 'status' => '1'],
            ['id' => 606, 'name' => 'THENI',                       'parent_id' => 32, 'status' => '1'],
            ['id' => 607, 'name' => 'THOOTHUKUDI',                 'parent_id' => 32, 'status' => '1'],
            ['id' => 608, 'name' => 'TIRUCHIRAPPALLI',             'parent_id' => 32, 'status' => '1'],
            ['id' => 609, 'name' => 'TIRUNELVELI',                 'parent_id' => 32, 'status' => '1'],
            ['id' => 610, 'name' => 'TIRUPPUR',                    'parent_id' => 32, 'status' => '1'],
            ['id' => 611, 'name' => 'TIRUVALLUR',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 612, 'name' => 'TIRUVANNAMALAI',              'parent_id' => 32, 'status' => '1'],
            ['id' => 613, 'name' => 'THIRUVARUR',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 614, 'name' => 'VELLORE',                     'parent_id' => 32, 'status' => '1'],
            ['id' => 615, 'name' => 'VILUPPURAM',                  'parent_id' => 32, 'status' => '1'],
            ['id' => 616, 'name' => 'VIRUDHUNAGAR',                'parent_id' => 32, 'status' => '1'],
            ['id' => 617, 'name' => 'AMBASSA',                     'parent_id' => 33, 'status' => '1'],
            ['id' => 618, 'name' => 'BISHRAMGANJ',                 'parent_id' => 33, 'status' => '1'],
            ['id' => 619, 'name' => 'KHOWAI',                      'parent_id' => 33, 'status' => '1'],
            ['id' => 620, 'name' => 'UDAIPUR',                     'parent_id' => 33, 'status' => '1'],
            ['id' => 621, 'name' => 'KAILASHAHAR',                 'parent_id' => 33, 'status' => '1'],
            ['id' => 622, 'name' => 'DHARMANAGAR',                 'parent_id' => 33, 'status' => '1'],
            ['id' => 623, 'name' => 'BELONIA',                     'parent_id' => 33, 'status' => '1'],
            ['id' => 624, 'name' => 'AGARTALA',                    'parent_id' => 33, 'status' => '1'],
            ['id' => 625, 'name' => 'ADILABAD',                    'parent_id' => 296,'status' => '1'],
            ['id' => 626, 'name' => 'HYDERABAD',                   'parent_id' => 296,'status' => '1'],
            ['id' => 627, 'name' => 'KARIMNAGAR',                  'parent_id' => 296,'status' => '1'],
            ['id' => 628, 'name' => 'KHAMMAM',                     'parent_id' => 296,'status' => '1'],
            ['id' => 629, 'name' => 'MAHBUBNAGAR',                 'parent_id' => 296,'status' => '1'],
            ['id' => 630, 'name' => 'SANGAREDDY',                  'parent_id' => 296,'status' => '1'],
            ['id' => 631, 'name' => 'NALGONDA',                    'parent_id' => 296,'status' => '1'],
            ['id' => 632, 'name' => 'NIZAMABAD',                   'parent_id' => 296,'status' => '1'],
            ['id' => 633, 'name' => 'VIKARABAD',                   'parent_id' => 296,'status' => '1'],
            ['id' => 634, 'name' => 'WARANGAL',                    'parent_id' => 296,'status' => '1'],
            ['id' => 635, 'name' => 'AZAMGARH',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 636, 'name' => 'MEERUT',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 637, 'name' => 'ALIPURDUAR',                  'parent_id' => 36, 'status' => '1'],
            ['id' => 638, 'name' => 'BANKURA',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 639, 'name' => 'BARDHAMAN',                   'parent_id' => 36, 'status' => '1'],
            ['id' => 640, 'name' => 'BIRBHUM',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 641, 'name' => 'COOCH BEHAR',                 'parent_id' => 36, 'status' => '1'],
            ['id' => 642, 'name' => 'DARJEELING',                  'parent_id' => 36, 'status' => '1'],
            ['id' => 643, 'name' => 'TAMLUK',                      'parent_id' => 36, 'status' => '1'],
            ['id' => 644, 'name' => 'HOOGHLY',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 645, 'name' => 'HOWRAH',                      'parent_id' => 36, 'status' => '1'],
            ['id' => 646, 'name' => 'JALPAIGURI',                  'parent_id' => 36, 'status' => '1'],
            ['id' => 647, 'name' => 'KOLKATA',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 648, 'name' => 'MALDA',                       'parent_id' => 36, 'status' => '1'],
            ['id' => 649, 'name' => 'BAHARAMPUR',                  'parent_id' => 36, 'status' => '1'],
            ['id' => 650, 'name' => 'KRISHNANAGAR',                'parent_id' => 36, 'status' => '1'],
            ['id' => 651, 'name' => 'BARASAT',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 652, 'name' => 'RAIGANJ',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 653, 'name' => 'PURULIA',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 654, 'name' => 'ALIPORE',                     'parent_id' => 36, 'status' => '1'],
            ['id' => 655, 'name' => 'BALURGHAT',                   'parent_id' => 36, 'status' => '1'],
            ['id' => 656, 'name' => 'MEDINIPUR',                   'parent_id' => 36, 'status' => '1'],
            ['id' => 657, 'name' => 'CHITRAKOOT',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 659, 'name' => 'RAMPUR',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 660, 'name' => 'JHANSI',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 661, 'name' => 'MIRZAPUR',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 663, 'name' => 'AURAIYA',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 664, 'name' => 'BADAUN',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 665, 'name' => 'BAHRAICH',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 666, 'name' => 'BIJNOR',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 667, 'name' => 'BALLIA',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 668, 'name' => 'BANDA',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 669, 'name' => 'BULANDSHAHR',                 'parent_id' => 34, 'status' => '1'],
            ['id' => 670, 'name' => 'FIROZABAD',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 671, 'name' => 'FARRUKHABAD',                 'parent_id' => 34, 'status' => '1'],
            ['id' => 672, 'name' => 'FATEHPUR',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 673, 'name' => 'NOIDA',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 674, 'name' => 'GHAZIABAD',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 675, 'name' => 'HAPUR',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 676, 'name' => 'HAMIRPUR',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 677, 'name' => 'HARDOI',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 678, 'name' => 'HATHRAS',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 679, 'name' => 'AMROHA',                      'parent_id' => 35, 'status' => '1'],
            ['id' => 680, 'name' => 'JAUNPUR',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 681, 'name' => 'AKBARPUR',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 682, 'name' => 'KANNAUJ',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 683, 'name' => 'KASGANJ',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 684, 'name' => 'MANJHANPUR',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 685, 'name' => 'LALITPUR',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 686, 'name' => 'LAKHIMPUR KHERI',             'parent_id' => 34, 'status' => '1'],
            ['id' => 687, 'name' => 'MAHARAJGANJ',                 'parent_id' => 34, 'status' => '1'],
            ['id' => 688, 'name' => 'MAHOBA',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 689, 'name' => 'MATHURA',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 690, 'name' => 'MUZAFFARNAGAR',               'parent_id' => 34, 'status' => '1'],
            ['id' => 691, 'name' => 'PILIBHIT',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 692, 'name' => 'RAE BARELI',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 693, 'name' => 'SITAPUR',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 694, 'name' => 'SHAHJAHANPUR',                'parent_id' => 34, 'status' => '1'],
            ['id' => 695, 'name' => 'SHAMLI',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 696, 'name' => 'SAMBHAL',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 697, 'name' => 'NAVGARH',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 698, 'name' => 'ROBERTSGANJ',                 'parent_id' => 34, 'status' => '1'],
            ['id' => 699, 'name' => 'GYANPUR',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 700, 'name' => 'SULTANPUR',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 701, 'name' => 'SHRAVASTI',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 702, 'name' => 'UNNAO',                       'parent_id' => 34, 'status' => '1'],
            ['id' => 703, 'name' => 'KHALILABAD',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 705, 'name' => 'CHANDIGARH',                  'parent_id' => 7,  'status' => '1'],
            ['id' => 706, 'name' => 'DADRA AND NAGAR HAVELI',      'parent_id' => 9,  'status' => '1'],
            ['id' => 707, 'name' => 'DAMAN AND DIU',               'parent_id' => 10, 'status' => '1'],
            ['id' => 709, 'name' => 'RAURKELA',                    'parent_id' => 27, 'status' => '1'],
            ['id' => 710, 'name' => 'BALRAMPUR',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 715, 'name' => 'MAINPURI',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 716, 'name' => 'SOMBHADRA',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 717, 'name' => 'SIWAN',                       'parent_id' => 6,  'status' => '1'],
            ['id' => 718, 'name' => 'Amroha',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 719, 'name' => 'AYODHAYA',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 720, 'name' => 'ETAWAH',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 721, 'name' => 'PRAYAGRAJ',                   'parent_id' => 34, 'status' => '1'],
            ['id' => 722, 'name' => 'BAGPAT',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 723, 'name' => 'BIJNAUR',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 724, 'name' => 'BUDAUN',                      'parent_id' => 34, 'status' => '1'],
            ['id' => 725, 'name' => 'MAHRAJGANJ',                  'parent_id' => 34, 'status' => '1'],
            ['id' => 726, 'name' => 'BHADOHI',                     'parent_id' => 34, 'status' => '1'],
            ['id' => 727, 'name' => 'UDAIGANJ',                    'parent_id' => 34, 'status' => '1'],
            ['id' => 728, 'name' => 'KALAGARH',                    'parent_id' => 35, 'status' => '1'],
        ];

        // Insert in chunks to avoid hitting MySQL's max_allowed_packet limit
        foreach (array_chunk($locations, 100) as $chunk) {
            DB::table('locations')->insert($chunk);
        }

        // Reset the auto-increment to continue from the max id
        DB::statement('ALTER TABLE locations AUTO_INCREMENT = 729;');
    }
}