<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your cart · MediServe</title><style>
*{box-sizing:border-box}body{margin:0;color:#18332c;font:15px/1.5 system-ui,sans-serif;background:#f7faf8}.wrap{width:min(960px,calc(100% - 32px));margin:auto}.head{height:72px;background:white;border-bottom:1px solid #e6eeeb}.head .wrap{height:100%;display:flex;align-items:center;justify-content:space-between}.brand{font-size:22px;font-weight:850;color:#087f5b;text-decoration:none}.brand span{color:#18332c}.back{color:#087f5b;font-weight:650;text-decoration:none}.title{margin:35px 0 18px}.title h1{margin:0;font-size:30px}.title p{color:#70817c;margin:5px 0}.panel{background:white;border:1px solid #e6eeeb;border-radius:15px;padding:20px}.item{display:flex;align-items:center;gap:16px;padding:15px 0;border-bottom:1px solid #edf1ef}.item:last-child{border:0}.pic{width:75px;height:75px;object-fit:contain;background:#f4f8f6;border-radius:10px;padding:7px}.info{flex:1}.info strong{display:block}.muted{color:#70817c;font-size:13px}.price{font-size:17px;font-weight:800}.remove{border:0;background:none;color:#b54754;cursor:pointer}.summary{display:flex;justify-content:space-between;padding:15px 0;font-size:18px;font-weight:800}.btn{display:block;text-align:center;background:#087f5b;color:white;text-decoration:none;font-weight:750;padding:13px;border-radius:9px}.empty{text-align:center;padding:45px 15px}.empty p{color:#70817c}.notice{background:#e8f8ee;padding:10px 13px;border-radius:9px;margin:14px 0}.qty-control{height:36px;display:flex;align-items:center;border:1px solid #c6e4d5;border-radius:8px;overflow:hidden}.qty-control button{width:34px;height:100%;border:0;background:#f4faf6;color:#087f5b;font-size:19px;cursor:pointer}.qty-control strong{min-width:28px;text-align:center}.feedback{position:fixed;right:20px;bottom:20px;padding:12px 18px;border-radius:10px;background:#073d31;color:white;opacity:0;transition:.2s;pointer-events:none}.feedback.visible{opacity:1}@media(max-width:540px){.item{gap:10px;flex-wrap:wrap}.pic{width:58px;height:58px}.item .price{font-size:14px}}
</style></head><body><header class="head"><div class="wrap"><a class="brand" href="{{ route('home') }}">medi<span>Serve</span></a><a class="back" href="{{ route('home') }}">Continue shopping →</a></div></header><main class="wrap"><div class="title"><h1>Your cart</h1><p>Review your items before checkout.</p></div>@if(session('shop_status'))<div class="notice">{{ session('shop_status') }}</div>@endif<div class="panel">
@php($total = 0)
@forelse($items as $item)
    @php($line = (float)($item->price ?? 0) * $item->quantity) @php($total += $line)
    <div class="item" data-cart-row="{{ $item->id }}"><img class="pic" src="{{ json_decode($item->images ?: '[]', true)[0] ?? '' }}" alt="" onerror="this.style.visibility='hidden'"><div class="info"><strong>{{ $item->name }}</strong><div class="muted">{{ $item->manufacturer ?: 'MediServe' }}</div><div class="qty-control" data-quantity-url="{{ route('cart.quantity', $item->id) }}"><input type="hidden" name="_token" value="{{ csrf_token() }}"><button type="button" data-qty-step="-1" aria-label="Decrease quantity">−</button><strong data-quantity>{{ $item->quantity }}</strong><button type="button" data-qty-step="1" aria-label="Increase quantity">+</button></div></div><div class="price" data-line-total>{{ $item->price !== null ? '₹'.number_format($line, 2) : 'Price on request' }}</div><form method="POST" action="{{ route('cart.remove', $item->id) }}">@csrf<button class="remove">Remove</button></form></div>
@empty<div class="empty"><div style="font-size:48px">🛒</div><h2>Your cart is waiting</h2><p>Add a few health essentials and they’ll appear here.</p><a class="btn" style="display:inline-block" href="{{ route('home') }}">Explore products</a></div>@endforelse
@if($items->isNotEmpty())<div class="summary"><span>Subtotal</span><span data-cart-subtotal>₹{{ number_format($total,2) }}</span></div><div class="muted" style="margin:0 0 15px">Delivery charges are calculated after your address is confirmed.</div><a class="btn" href="{{ route('checkout') }}">Continue to checkout</a>@endif
</div></main><div class="feedback cart-feedback" role="status" aria-live="polite"></div>@include('storefront.cart-scripts')</body></html>
